version: '3.3'

services:

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - discovery

  discovery:
    image: "consul:1.8"
    environment:
      - CONSUL_LOCAL_CONFIG={"log_level":"info"}

  redis:
    image: "redis:latest"

  postgres-authentication:
    image: "postgres:10"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  postgres-user-collections:
    image: "postgres:10"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  postgres-scores:
    image: "postgres:10"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  authentication:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - redis
      - postgres-authentication

  cards_0:
    build:
      context: ./cards
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - discovery

  cards_1:
    build:
      context: ./cards
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - discovery

  user-collections:
    build:
      context: ./user-collections
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - discovery
      - postgres-user-collections
      - authentication

  scores:
    build:
      context: ./scores
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - discovery
      - postgres-scores


